export const CartTypes = {
    ADD_CART: "ADD_CART",
    UPDATE_CART: "UPDATE_CART",
    DELETE_CART: "DELETE_CART",
    GET_NUMBER_CART: "GET_NUMBER_CART",
    INCREASE_QUANTITY: "INCREASE_QUANTITY",
    DECREASE_QUANTITY: "DECREASE_QUANTITY",
};
