export const OrderTypes = {
    CREATE_ORDER: "CREATE_ORDER",
    FETCH_ORDER: "FETCH_ORDER",
    SINGLE_ORDER: "SINGLE_ORDER",
    REMOVE_SINGLE_ORDER: "REMOVE_SINGLE_ORDER",
    ORDER_FORM_VALIDATION: "ORDER_FORM_VALIDATION",
};
