export const OrderTypes = {
    CREATE_ORDER: "CREATE_ORDER",
    REMOVE_CREATE_ORDER: "CREATE_ORDER",
    FETCH_ORDER: "FETCH_ORDER",
    SINGLE_ORDER: "SINGLE_ORDER",
    USER_GET_ORDERS: "USER_GET_ORDERS",
    USER_GET_SINGLE_ORDERS: "USER_GET_SINGLE_ORDERS",
    REMOVE_SINGLE_ORDER: "REMOVE_SINGLE_ORDER",
    ORDER_FORM_VALIDATION: "ORDER_FORM_VALIDATION",
};
