export const ProductTypes = {
  FETCH_PRODUCT: "FETCH_PRODUCT",
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_SINGLE_PRODUCT: "GET_SINGLE_PRODUCT",
  REMOVE_PRODUCT: "REMOVE_PRODUCT",
  STORE_PRODUCT: "STORE_PRODUCT",
  VALIDATION_ERRORS: "VALIDATION_ERRORS",
  PRODUCT_RATING: "PRODUCT_RATING",
  PRODUCT_RATING_VALIDATION_ERRORS: "PRODUCT_RATING_VALIDATION_ERRORS",
};
