export const UserTypes = {
    //Auth
    USER_LOGIN: "USER_LOGIN",
    USER_LOGOUT: "USER_LOGOUT",
    USER_REGISTERED: "USER_REGISTERED",
    LOGIN_VALIDATION: "LOGIN_VALIDATION",
    REGISTERED_VALIDATION: "REGISTERED_VALIDATION",

    //Orders
    ADD_TO_WHISHLIST: "ADD_TO_WHISHLIST",
    DELETE_FROM_WHISHLIST: "DELETE_FROM_WHISHLIST",
    EMPTY_WHISHLIST: "EMPTY_WHISHLIST",

    //Wishlist
    ADD_TO_WHISHLIST: "ADD_TO_WHISHLIST",
    FETCH_WHISHLIST: "FETCH_WHISHLIST",
    DELETE_FROM_WHISHLIST: "DELETE_FROM_WHISHLIST",
    EMPTY_WHISHLIST: "EMPTY_WHISHLIST",
};
