export const UserTypes = {
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  USER_REGISTERED: "USER_REGISTERED",
  LOGIN_VALIDATION: "LOGIN_VALIDATION",
  REGISTERED_VALIDATION: "REGISTERED_VALIDATION",
};
